### ISSUE TITLE
"doubt"   storing in single folder

### ISSUE THREAD

**Issue by Rajkumar-427** [shibli2700/Rekon#18]
hi @shibli2700, As i had modified enum.sh and making the output to store in single folder with the domain name ,but i am stuck at the response.sh which is grabbing alive.txt as input which in my case located inside the domain folder, so to grab that file inside the domain folder what shud i make the changes in response.sh

**Comment by shibli2700** [comment]
Hi @Rajkumar-427 ,

Recently I made some major changes in the `response.sh` file and have introduced concurrency to provide better performance, refer the following line in the latest version of `response.sh`

```bash
cat $1 | xargs -P 50 -n 1 -I {} bash -c "fetch_resp {}"
```

Now you can explicitly provide the path where your alive.txt is stored e.g.

```bash
./response.sh sub-dir/alive.txt
```

**Comment by shibli2700** [comment]
Please open another issue if u face any problems while executing the script
