### ISSUE TITLE
curl issue !

### ISSUE THREAD

**Issue by Dujunayan** [shibli2700/Rekon#2]
<img width="623" alt="Screen Shot 2019-11-18 at 10 18 07" src="https://user-images.githubusercontent.com/51866960/69040019-5a978500-09ed-11ea-94f1-5635aa481b28.png">

**Comment by shibli2700** [comment]
Hello, can you specify the filename

**Comment by shibli2700** [comment]
And can you please elaborate a little about the issue?

**Comment by xYantix** [comment]
This looks a lot like an issue with your input. If you could include the command you ran as well as the output from a "ls" command from the directory you're running it from that would help a lot with troubleshooting.
