### ISSUE TITLE
[enhacement] Consider replacing the relative-url-extractor tool 

### ISSUE THREAD

**Issue by Hax0rG1rl** [shibli2700/Rekon#3]
Hi, 

Nice work. Please consider using an alternative for this relative-url-extractor tool which is a ruby script.    On kali, ruby is a complete pain in the neck because of its lack of portability. 

Otherwise, at least document which version of ruby you are using to have this one working. Knowing the developer of the tool, I doubt he will refactor it to work with Ruby 2.6.2 version but I have seen miracles b4. 

Thanks!

**Comment by shibli2700** [comment]
Thanks for pointing it out, I will definitely try to add an alternate tool or a custom script to do the same, will notify you when it's done.

**Comment by shibli2700** [comment]
Or if you know a better tool you can create a pull request, I LL be more than happy to merge it.
