### ISSUE TITLE
Question regarding response.sh

### ISSUE THREAD

**Issue by dark-warlord14** [shibli2700/Rekon#5]
as httprobe gives us http and https urls in alive.txt
are we storing responses for both of them separately or are they overriding each other?
I am looking to embed this in my workflow
just stuck here
if you can answer this it will be a great help
in the mean time I will check it out myself 
Great work btw
Happy hacking!!

**Comment by shibli2700** [comment]
Thank you 🙂

We are storing the responses from both HTTP and HTTPS because in the past, I have encountered cases where two completely different responses were getting served on 80 and 443.

**Comment by dark-warlord14** [comment]
Are you sure?
I just made some changes to response.sh to store both http and https reponse and headers. But this changes lot of thing for the next script. Will you take a look at the changes I made?
also i thought you are not storing the response. Thats the only reason I made changes
I will now try to hack up the jsfiles script.
let me know what you think.

**Comment by shibli2700** [comment]
Yes I will give it a look and will merge it after review.

Maybe it won't change other scripts coz currently they are just enumerating the whole directories.

Thanks 👍

**Comment by dark-warlord14** [comment]
no but i had to change the name of headers and response body files and separate http and https.
this changes things.
I am looking into it too.
