### ISSUE TITLE
Issues while running jsfiles.sh & endpoints.sh

### ISSUE THREAD

**Issue by 0-0eth0** [shibli2700/Rekon#7]
Issue while running jsfiles.sh

`mkdir: cannot create directory ‘scriptsresponse/ex.com/’: File exists
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23627  100 23627    0     0  56795      0 --:--:-- --:--:-- --:--:-- 56932
mkdir: cannot create directory ‘scriptsresponse/ex.com/’: File exists
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 66328  100 66328    0     0   139k      0 --:--:-- --:--:-- --:--:--  138k
mkdir: cannot create directory ‘scriptsresponse/ex.com/’: File exists
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 80784  100 80784    0     0   172k      0 --:--:-- --:--:-- --:--:--  172k
mkdir: cannot create directory ‘scriptsresponse/ex.com/’: File exists
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   382  100   382    0     0    907      0 --:--:-- --:--:-- --:--:--   907
mkdir: cannot create directory ‘scriptsresponse/ex.com/’: File exists
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3254  100  3254    0     0   8196      0 --:--:-- --:--:-- --:--:--  8196
mkdir: cannot create directory ‘scriptsresponse/ex.com/’: File exists
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left`

issues while running endpoints.sh
`Traceback (most recent call last):
ruby: No such file or directory -- /root/relative-url-extractor/extract.rb (LoadError)
Traceback (most recent call last):
ruby: No such file or directory -- /root/relative-url-extractor/extract.rb (LoadError)
Traceback (most recent call last):
ruby: No such file or directory -- /root/relative-url-extractor/extract.rb (LoadError)
Traceback (most recent call last):
ruby: No such file or directory -- /root/relative-url-extractor/extract.rb (LoadError)
Traceback (most recent call last):
ruby: No such file or directory -- /root/relative-url-extractor/extract.rb (LoadError)
Traceback (most recent call last):
ruby: No such file or directory -- /root/relative-url-extractor/extract.rb (LoadError)
Traceback (most recent call last):
ruby: No such file or directory -- /root/relative-url-extractor/extract.rb (LoadError)
Traceback (most recent call last):
ruby: No such file or directory -- /root/relative-url-extractor/extract.rb (LoadError)
Traceback (most recent call last):
ruby: No such file or directory -- /root/relative-url-extractor/extract.rb (LoadError)`

P.S url extractor is working fine or installed correctly.

**Comment by KathanP19** [comment]
For fixing jsfiles.sh error try running sudo on it as the error says that file already exist, you can delete it and start again

For fixing the endpoints.sh error it says that file doesn't exist put the relative-url-extractor directory in root 

Check the error properly ,the error it self tell you how you can fix them.
